### PR TITLE
feat: remove webpack optimization if present

### LINKED ISSUE #88: Remove optimization object
When we bundle specs, we usually cannot use the Webpack optimizations https://webpack.js.org/configuration/optimization/

So we should delete this property from the webpack object if present

### PR DESCRIPTION
**Pull request by bahmutov**
- closes #88

### CODE REVIEW

**Comment by Bkucera** [comment]
so we let users set `mode: "production"` but don't let them set optimization? Won't `mode: "production"` enable optimization by default?

**Comment by bahmutov** [comment]
Yup we have to strip optimizations since things like chunking are likely to fail anyway

**Comment by Bkucera** [comment]
shouldn't we set it to `optimization: false` instead?

**Comment by bahmutov** [comment]
I assume since it is an object we should remove it and not change to Boolean

**Comment by Bkucera** [comment]
nice, I misread the docs

**Comment by brian-mann** [comment]
Closing per my comment here: https://github.com/cypress-io/cypress-webpack-preprocessor/issues/88#issuecomment-630064134

**Pull request closed without merging**
